/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/trigger/nightly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Nightly */
        post: operations["trigger_nightly_admin_trigger_nightly_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create a new account via Supabase Auth.
         *
         *     Returns a session (access_token + refresh_token) on success, or a
         *     confirmation-pending response if email verification is enabled.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email + password for an access + refresh token pair.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a refresh token for a new access + refresh token pair.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Readings */
        post: operations["post_readings_api_v1_readings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_v1_preferences_get"];
        /** Put Preferences */
        put: operations["put_preferences_api_v1_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_api_v1_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Schedules
         * @description Unified endpoint: returns all appliance schedules for the
         *     authenticated user. The integration polls this once per day.
         */
        get: operations["get_all_schedules_api_v1_schedules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appliances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Appliances */
        get: operations["list_appliances_api_v1_appliances_get"];
        put?: never;
        /** Create Appliance */
        post: operations["create_appliance_api_v1_appliances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appliances/{appliance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Appliance */
        put: operations["update_appliance_api_v1_appliances__appliance_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appliances/{appliance_id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Appliance Readings */
        post: operations["post_appliance_readings_api_v1_appliances__appliance_id__readings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appliances/{appliance_id}/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Constraints */
        post: operations["set_constraints_api_v1_appliances__appliance_id__constraints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appliances/{appliance_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Appliance Schedule */
        get: operations["get_appliance_schedule_api_v1_appliances__appliance_id__schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/create-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Checkout */
        post: operations["create_checkout_billing_create_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portal */
        get: operations["get_portal_billing_portal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Webhook */
        post: operations["stripe_webhook_billing_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rates */
        get: operations["get_rates_api_v1_rates_get"];
        /** Put Rates */
        put: operations["put_rates_api_v1_rates_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Weather
         * @description Store the user's HA weather forecast for tonight's optimization.
         *
         *     Existing forecast rows are overwritten (single-latest-row-per-user
         *     semantics). Missing optional arrays (humidity, wind) are stored as
         *     null — the optimizer treats those as "use defaults".
         */
        post: operations["push_weather_api_v1_weather_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplianceCreate */
        ApplianceCreate: {
            /** Appliance Type */
            appliance_type: string;
            /** Name */
            name: string;
            /**
             * Config
             * @default {}
             */
            config: Record<string, never>;
        };
        /** ApplianceReading */
        ApplianceReading: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** State */
            state: string;
            /** Value */
            value: number;
            /** Power Watts */
            power_watts?: number | null;
            /** Metadata */
            metadata?: Record<string, never> | null;
        };
        /** ApplianceUpdate */
        ApplianceUpdate: {
            /** Name */
            name?: string | null;
            /** Config */
            config?: Record<string, never> | null;
        };
        /** CheckoutResponse */
        CheckoutResponse: {
            /** Url */
            url: string;
        };
        /** CreateCheckoutRequest */
        CreateCheckoutRequest: {
            /** Tier */
            tier: string;
            /** Success Url */
            success_url: string;
            /** Cancel Url */
            cancel_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HvacScheduleBody
         * @description The HVAC-specific schedule shape served by GET /api/v1/schedule.
         *
         *     Typed explicitly (vs. a free-form dict) so OpenAPI emits a precise
         *     JSON schema for the response, which lets the frontend's contract
         *     test catch drift on these field names + array shapes.
         */
        HvacScheduleBody: {
            /** Intervals */
            intervals: number[];
            /** High Temps */
            high_temps: number[];
            /** Low Temps */
            low_temps: number[];
            /** Temp Trajectory */
            temp_trajectory?: number[] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Location Zip */
            location_zip: string;
            /** Home Size Sqft */
            home_size_sqft: number;
            /** Pricing Location */
            pricing_location: number;
            /** Timezone */
            timezone: string;
            /** Subscription Tier */
            subscription_tier: string;
            /**
             * Weather Entity Id
             * @default
             */
            weather_entity_id: string;
        };
        /** PortalResponse */
        PortalResponse: {
            /** Url */
            url: string;
        };
        /** PreferencesResponse */
        PreferencesResponse: {
            /** Base Temperature */
            base_temperature: number;
            /** Savings Level */
            savings_level: number;
            /** Time Away */
            time_away: string;
            /** Time Home */
            time_home: string;
            /** Optimization Mode */
            optimization_mode: string;
            /** Hourly High Temps F */
            hourly_high_temps_f?: number[] | null;
            /** Hourly Low Temps F */
            hourly_low_temps_f?: number[] | null;
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /** Base Temperature */
            base_temperature?: number | null;
            /** Savings Level */
            savings_level?: number | null;
            /** Time Away */
            time_away?: string | null;
            /** Time Home */
            time_home?: string | null;
            /** Optimization Mode */
            optimization_mode?: string | null;
            /** Hourly High Temps F */
            hourly_high_temps_f?: number[] | null;
            /** Hourly Low Temps F */
            hourly_low_temps_f?: number[] | null;
        };
        /** RatesResponse */
        RatesResponse: {
            /** Pricing Location */
            pricing_location: number;
            /** Intervals */
            intervals: number[];
            /** Rates Cents Per Kwh */
            rates_cents_per_kwh: number[];
            /** Source */
            source: string;
            /** Hourly Rates Cents Per Kwh */
            hourly_rates_cents_per_kwh?: number[] | null;
            /**
             * Unit
             * @default cents/kWh
             */
            unit: string;
        };
        /** RatesUpdate */
        RatesUpdate: {
            /** Hourly Rates Cents Per Kwh */
            hourly_rates_cents_per_kwh?: number[] | null;
        };
        /** ReadingsResponse */
        ReadingsResponse: {
            /** Accepted */
            accepted: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            /** Date */
            date: string;
            schedule: components["schemas"]["HvacScheduleBody"];
            /** Mode */
            mode: string;
            /** Estimated Savings Pct */
            estimated_savings_pct: number;
            /** Model Confidence */
            model_confidence?: number | null;
            /** Generated At */
            generated_at: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /**
             * Source
             * @default optimization
             */
            source: string;
        };
        /** SensorReading */
        SensorReading: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Indoor Temp */
            indoor_temp: number;
            /** Hvac State */
            hvac_state: string;
            /** Indoor Humidity */
            indoor_humidity?: number | null;
            /** Outdoor Temp */
            outdoor_temp?: number | null;
            /** Target Temp */
            target_temp?: number | null;
            /** Fan Mode */
            fan_mode?: string | null;
            /** Power Watts */
            power_watts?: number | null;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Location Zip */
            location_zip?: string | null;
            /** Home Size Sqft */
            home_size_sqft?: number | null;
            /** Pricing Location */
            pricing_location?: number | null;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Location Zip */
            location_zip?: string | null;
            /** Home Size Sqft */
            home_size_sqft?: number | null;
            /** Pricing Location */
            pricing_location?: number | null;
            /** Timezone */
            timezone?: string | null;
            /** Weather Entity Id */
            weather_entity_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeatherForecast */
        WeatherForecast: {
            /** Hourly Temps F */
            hourly_temps_f: number[];
            /** Hourly Humidity */
            hourly_humidity?: number[] | null;
            /** Hourly Wind Mph */
            hourly_wind_mph?: number[] | null;
        };
        /** WeatherPush */
        WeatherPush: {
            forecast: components["schemas"]["WeatherForecast"];
        };
        /** WeatherPushResponse */
        WeatherPushResponse: {
            /** Accepted Hours */
            accepted_hours: number;
            /** Pushed At */
            pushed_at: string;
        };
        /** ReadingsBatch */
        app__routes__appliances__ReadingsBatch: {
            /** Readings */
            readings: components["schemas"]["ApplianceReading"][];
        };
        /** ReadingsBatch */
        app__routes__readings__ReadingsBatch: {
            /** Readings */
            readings: components["schemas"]["SensorReading"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_nightly_admin_trigger_nightly_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_readings_api_v1_readings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__routes__readings__ReadingsBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_v1_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
        };
    };
    put_preferences_api_v1_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_api_v1_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
        };
    };
    get_all_schedules_api_v1_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_appliances_api_v1_appliances_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_appliance_api_v1_appliances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplianceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_appliance_api_v1_appliances__appliance_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appliance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplianceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_appliance_readings_api_v1_appliances__appliance_id__readings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appliance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__routes__appliances__ReadingsBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_constraints_api_v1_appliances__appliance_id__constraints_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appliance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_appliance_schedule_api_v1_appliances__appliance_id__schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appliance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_billing_create_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portal_billing_portal_get: {
        parameters: {
            query?: {
                return_url?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_billing_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_rates_api_v1_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatesResponse"];
                };
            };
        };
    };
    put_rates_api_v1_rates_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_weather_api_v1_weather_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeatherPush"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherPushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
